---
- hosts: test1
  tasks:
    - name: Install shit
      become: True
      apt:
        name: apache2
        state: latest

    - name: Start shit
      become: True
      service:
        name: apache2
        state: started
